/**
 * ชุดวัตถุดิบตั้งต้นของ "ชามจัดเอง" 6 ขั้น × 10 ตัวเลือก
 *
 * 🔴 per100 = ค่าต่อ 100 ก./มล. ตามฐานของคลังวัตถุดิบ (ไม่ใช่ต่อที่)
 *    ตัวเลขชุดนี้เป็น "ค่ามาตรฐานเริ่มต้น" — ทุกแถวถูกติดธง isEstimate ไว้
 *    จนกว่าครัวจะชั่งของจริงแล้วแก้ในหลังบ้าน
 * 🔴 portionSize = ปริมาณต่อ 1 ที่ (unit = pc คือจำนวนชิ้น ต้องมี gramsPerPiece ด้วย)
 * 🔴 price = บาทที่บวกเพิ่มต่อ 1 ที่ · 0 = รวมอยู่ในราคาฐานของชามแล้ว
 */

export type BowlSeedRow = {
  slug: string;
  name: string;
  nameEn: string;
  displayName?: string;
  step: string;
  role: string;
  unit: string;
  portionSize: number;
  gramsPerPiece: number | null;
  price: number;
  sort: number;
  per100: { calories: number; protein: number; carbs: number; fat: number; sodium: number; sugar: number };
  allergens: string[];
};

export const BOWL_SEED: BowlSeedRow[] = [
  { slug: "rice_jasmine", name: "ข้าวหอมมะลิ", nameEn: "Jasmine Rice", step: "base", role: "carb",
    unit: "g", portionSize: 150, gramsPerPiece: null, price: 0, sort: 1,
    per100: { calories: 133.3, protein: 2.7, carbs: 29.3, fat: 0.3, sodium: 3.3, sugar: 0.0 },
    allergens: [] },
  { slug: "rice_brown", name: "ข้าวกล้อง", nameEn: "Brown Rice", step: "base", role: "carb",
    unit: "g", portionSize: 150, gramsPerPiece: null, price: 0, sort: 2,
    per100: { calories: 120.0, protein: 2.7, carbs: 25.3, fat: 1.0, sodium: 3.3, sugar: 0.0 },
    allergens: [] },
  { slug: "rice_riceberry", name: "ข้าวไรซ์เบอร์รี่", nameEn: "Riceberry Rice", step: "base", role: "carb",
    unit: "g", portionSize: 150, gramsPerPiece: null, price: 5, sort: 3,
    per100: { calories: 116.7, protein: 3.0, carbs: 24.0, fat: 1.0, sodium: 3.3, sugar: 0.0 },
    allergens: [] },
  { slug: "rice_jp", name: "ข้าวญี่ปุ่น", nameEn: "Japanese Rice", step: "base", role: "carb",
    unit: "g", portionSize: 150, gramsPerPiece: null, price: 5, sort: 4,
    per100: { calories: 140.0, protein: 2.7, carbs: 30.7, fat: 0.3, sodium: 3.3, sugar: 0.0 },
    allergens: [] },
  { slug: "quinoa", name: "คีนัว", nameEn: "Quinoa", step: "base", role: "carb",
    unit: "g", portionSize: 120, gramsPerPiece: null, price: 15, sort: 5,
    per100: { calories: 133.3, protein: 5.0, carbs: 23.3, fat: 2.1, sodium: 8.3, sugar: 0.8 },
    allergens: [] },
  { slug: "sweet_potato", name: "มันหวาน", nameEn: "Sweet Potato", step: "base", role: "carb",
    unit: "g", portionSize: 130, gramsPerPiece: null, price: 10, sort: 6,
    per100: { calories: 100.0, protein: 1.5, carbs: 23.1, fat: 0.2, sodium: 42.3, sugar: 6.9 },
    allergens: [] },
  { slug: "potato", name: "มันฝรั่ง", nameEn: "Potato", step: "base", role: "carb",
    unit: "g", portionSize: 130, gramsPerPiece: null, price: 10, sort: 7,
    per100: { calories: 92.3, protein: 2.3, carbs: 20.8, fat: 0.2, sodium: 7.7, sugar: 0.8 },
    allergens: [] },
  { slug: "corn_base", name: "ข้าวโพด (ฐาน)", displayName: "ข้าวโพด", nameEn: "Sweet Corn", step: "base", role: "carb",
    unit: "g", portionSize: 120, gramsPerPiece: null, price: 10, sort: 8,
    per100: { calories: 91.7, protein: 2.9, carbs: 20.0, fat: 1.2, sodium: 12.5, sugar: 5.0 },
    allergens: [] },
  { slug: "mixed_rice", name: "ข้าวผสม", nameEn: "Mixed Rice", step: "base", role: "carb",
    unit: "g", portionSize: 150, gramsPerPiece: null, price: 5, sort: 9,
    per100: { calories: 126.7, protein: 3.0, carbs: 26.7, fat: 0.7, sodium: 3.3, sugar: 0.0 },
    allergens: [] },
  { slug: "mixed_greens", name: "ผักสลัดรวม", nameEn: "Mixed Greens", step: "base", role: "carb",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 0, sort: 10,
    per100: { calories: 58.3, protein: 4.2, carbs: 10.0, fat: 0.7, sodium: 41.7, sugar: 3.3 },
    allergens: [] },
  { slug: "chicken_grill", name: "ไก่ย่าง", nameEn: "Grilled Chicken", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 45, sort: 1,
    per100: { calories: 165.0, protein: 31.0, carbs: 0.0, fat: 3.6, sodium: 320.0, sugar: 0.0 },
    allergens: [] },
  { slug: "chicken_poach", name: "ไก่ต้ม", nameEn: "Poached Chicken", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 45, sort: 2,
    per100: { calories: 140.0, protein: 29.0, carbs: 0.0, fat: 2.5, sodium: 90.0, sugar: 0.0 },
    allergens: [] },
  { slug: "pork_grill", name: "หมูย่าง", nameEn: "Grilled Pork", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 45, sort: 3,
    per100: { calories: 210.0, protein: 27.0, carbs: 1.0, fat: 11.0, sodium: 340.0, sugar: 1.0 },
    allergens: [] },
  { slug: "pork_boil", name: "หมูต้ม", nameEn: "Boiled Pork", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 45, sort: 4,
    per100: { calories: 180.0, protein: 26.0, carbs: 0.0, fat: 8.0, sodium: 80.0, sugar: 0.0 },
    allergens: [] },
  { slug: "shrimp", name: "กุ้ง", nameEn: "Shrimp", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 65, sort: 5,
    per100: { calories: 99.0, protein: 21.0, carbs: 0.0, fat: 1.2, sodium: 180.0, sugar: 0.0 },
    allergens: ["shrimp", "shellfish"] },
  { slug: "salmon", name: "แซลมอน", nameEn: "Salmon", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 79, sort: 6,
    per100: { calories: 220.0, protein: 24.0, carbs: 0.0, fat: 13.0, sodium: 60.0, sugar: 0.0 },
    allergens: ["fish"] },
  { slug: "tuna", name: "ทูน่า", nameEn: "Tuna", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 55, sort: 7,
    per100: { calories: 130.0, protein: 28.0, carbs: 0.0, fat: 1.5, sodium: 200.0, sugar: 0.0 },
    allergens: ["fish"] },
  { slug: "white_fish", name: "ปลาขาว", nameEn: "White Fish", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 49, sort: 8,
    per100: { calories: 110.0, protein: 23.0, carbs: 0.0, fat: 1.8, sodium: 75.0, sugar: 0.0 },
    allergens: ["fish"] },
  { slug: "egg_protein", name: "ไข่", nameEn: "Egg", step: "protein", role: "protein",
    unit: "pc", portionSize: 2, gramsPerPiece: 50, price: 20, sort: 9,
    per100: { calories: 150.0, protein: 13.0, carbs: 1.0, fat: 10.0, sodium: 140.0, sugar: 0.5 },
    allergens: ["egg"] },
  { slug: "tofu", name: "เต้าหู้", nameEn: "Tofu", step: "protein", role: "protein",
    unit: "g", portionSize: 100, gramsPerPiece: null, price: 25, sort: 10,
    per100: { calories: 120.0, protein: 13.0, carbs: 3.0, fat: 7.0, sodium: 20.0, sugar: 0.5 },
    allergens: ["soy"] },
  { slug: "broccoli", name: "บรอกโคลี", nameEn: "Broccoli", step: "veggies", role: "veg",
    unit: "g", portionSize: 70, gramsPerPiece: null, price: 0, sort: 1,
    per100: { calories: 42.9, protein: 3.6, carbs: 8.6, fat: 0.4, sodium: 42.9, sugar: 2.1 },
    allergens: [] },
  { slug: "carrot", name: "แครอท", nameEn: "Carrot", step: "veggies", role: "veg",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 0, sort: 2,
    per100: { calories: 50.0, protein: 1.2, carbs: 11.7, fat: 0.3, sodium: 91.7, sugar: 7.5 },
    allergens: [] },
  { slug: "corn_veg", name: "ข้าวโพด (ผัก)", displayName: "ข้าวโพด", nameEn: "Corn", step: "veggies", role: "veg",
    unit: "g", portionSize: 70, gramsPerPiece: null, price: 0, sort: 3,
    per100: { calories: 100.0, protein: 3.6, carbs: 22.9, fat: 1.4, sodium: 14.3, sugar: 5.7 },
    allergens: [] },
  { slug: "cherry_tomato", name: "เชอร์รี่โทเมโท", nameEn: "Cherry Tomato", step: "veggies", role: "veg",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 0, sort: 4,
    per100: { calories: 33.3, protein: 1.7, carbs: 6.7, fat: 0.3, sodium: 8.3, sugar: 5.0 },
    allergens: [] },
  { slug: "purple_cabbage", name: "กะหล่ำม่วง", nameEn: "Purple Cabbage", step: "veggies", role: "veg",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 0, sort: 5,
    per100: { calories: 41.7, protein: 1.7, carbs: 10.0, fat: 0.2, sodium: 33.3, sugar: 5.0 },
    allergens: [] },
  { slug: "cucumber", name: "แตงกวา", nameEn: "Cucumber", step: "veggies", role: "veg",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 0, sort: 6,
    per100: { calories: 20.0, protein: 0.8, carbs: 4.2, fat: 0.2, sodium: 3.3, sugar: 2.5 },
    allergens: [] },
  { slug: "pumpkin", name: "ฟักทอง", nameEn: "Pumpkin", step: "veggies", role: "veg",
    unit: "g", portionSize: 70, gramsPerPiece: null, price: 0, sort: 7,
    per100: { calories: 50.0, protein: 1.4, carbs: 11.4, fat: 0.1, sodium: 1.4, sugar: 5.0 },
    allergens: [] },
  { slug: "mushroom", name: "เห็ด", nameEn: "Mushroom", step: "veggies", role: "veg",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 0, sort: 8,
    per100: { calories: 33.3, protein: 4.2, carbs: 5.0, fat: 0.5, sodium: 8.3, sugar: 1.7 },
    allergens: [] },
  { slug: "bell_pepper", name: "พริกหวาน", nameEn: "Bell Pepper", step: "veggies", role: "veg",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 0, sort: 9,
    per100: { calories: 41.7, protein: 1.7, carbs: 8.3, fat: 0.3, sodium: 6.7, sugar: 5.8 },
    allergens: [] },
  { slug: "edamame_veg", name: "ถั่วแระ (ผัก)", displayName: "ถั่วแระ", nameEn: "Edamame", step: "veggies", role: "veg",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 0, sort: 10,
    per100: { calories: 150.0, protein: 13.3, carbs: 11.7, fat: 6.7, sodium: 8.3, sugar: 2.5 },
    allergens: ["soy"] },
  { slug: "avocado", name: "อะโวคาโด", nameEn: "Avocado", step: "toppings", role: "fat",
    unit: "g", portionSize: 50, gramsPerPiece: null, price: 25, sort: 1,
    per100: { calories: 320.0, protein: 4.0, carbs: 18.0, fat: 30.0, sodium: 14.0, sugar: 1.0 },
    allergens: [] },
  { slug: "boiled_egg", name: "ไข่ต้ม", nameEn: "Boiled Egg", step: "toppings", role: "fat",
    unit: "pc", portionSize: 1, gramsPerPiece: 50, price: 15, sort: 2,
    per100: { calories: 156.0, protein: 12.0, carbs: 1.2, fat: 10.0, sodium: 124.0, sugar: 1.0 },
    allergens: ["egg"] },
  { slug: "edamame_top", name: "ถั่วแระ (ท็อปปิ้ง)", displayName: "ถั่วแระ", nameEn: "Edamame", step: "toppings", role: "fat",
    unit: "g", portionSize: 60, gramsPerPiece: null, price: 15, sort: 3,
    per100: { calories: 150.0, protein: 13.3, carbs: 11.7, fat: 6.7, sodium: 8.3, sugar: 2.5 },
    allergens: ["soy"] },
  { slug: "seaweed", name: "สาหร่าย", nameEn: "Seaweed", step: "toppings", role: "fat",
    unit: "g", portionSize: 40, gramsPerPiece: null, price: 10, sort: 4,
    per100: { calories: 50.0, protein: 5.0, carbs: 7.5, fat: 0.8, sodium: 450.0, sugar: 1.2 },
    allergens: [] },
  { slug: "kimchi", name: "กิมจิ", nameEn: "Kimchi", step: "toppings", role: "fat",
    unit: "g", portionSize: 40, gramsPerPiece: null, price: 15, sort: 5,
    per100: { calories: 62.5, protein: 3.8, carbs: 10.0, fat: 0.8, sodium: 1000.0, sugar: 3.8 },
    allergens: ["fish"] },
  { slug: "pickled_cucumber", name: "แตงกวาดอง", nameEn: "Pickled Cucumber", step: "toppings", role: "fat",
    unit: "g", portionSize: 40, gramsPerPiece: null, price: 10, sort: 6,
    per100: { calories: 37.5, protein: 0.8, carbs: 7.5, fat: 0.0, sodium: 875.0, sugar: 5.0 },
    allergens: [] },
  { slug: "pickled_carrot", name: "แครอทดอง", nameEn: "Pickled Carrot", step: "toppings", role: "fat",
    unit: "g", portionSize: 40, gramsPerPiece: null, price: 10, sort: 7,
    per100: { calories: 62.5, protein: 1.0, carbs: 15.0, fat: 0.0, sodium: 750.0, sugar: 11.2 },
    allergens: [] },
  { slug: "almond", name: "อัลมอนด์", nameEn: "Almond", step: "toppings", role: "fat",
    unit: "g", portionSize: 15, gramsPerPiece: null, price: 20, sort: 8,
    per100: { calories: 600.0, protein: 20.0, carbs: 20.0, fat: 53.3, sodium: 0.0, sugar: 4.7 },
    allergens: ["treenut"] },
  { slug: "cashew", name: "เม็ดมะม่วง", nameEn: "Cashew", step: "toppings", role: "fat",
    unit: "g", portionSize: 15, gramsPerPiece: null, price: 20, sort: 9,
    per100: { calories: 566.7, protein: 18.0, carbs: 33.3, fat: 46.7, sodium: 20.0, sugar: 6.7 },
    allergens: ["treenut"] },
  { slug: "pumpkin_seeds", name: "เมล็ดฟักทอง", nameEn: "Pumpkin Seeds", step: "toppings", role: "fat",
    unit: "g", portionSize: 15, gramsPerPiece: null, price: 20, sort: 10,
    per100: { calories: 566.7, protein: 30.0, carbs: 13.3, fat: 46.7, sodium: 20.0, sugar: 2.0 },
    allergens: [] },
  { slug: "sesame", name: "งาญี่ปุ่น", nameEn: "Sesame", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 1,
    per100: { calories: 400.0, protein: 6.7, carbs: 13.3, fat: 36.7, sodium: 1066.7, sugar: 10.0 },
    allergens: ["sesame", "soy"] },
  { slug: "lemon_herb", name: "เลมอนเฮิร์บ", nameEn: "Lemon Herb", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 2,
    per100: { calories: 200.0, protein: 0.7, carbs: 6.7, fat: 20.0, sodium: 600.0, sugar: 3.3 },
    allergens: [] },
  { slug: "spicy_thai", name: "ซีฟู้ดไทย", nameEn: "Spicy Thai", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 3,
    per100: { calories: 150.0, protein: 1.7, carbs: 26.7, fat: 1.7, sodium: 1733.3, sugar: 20.0 },
    allergens: ["fish"] },
  { slug: "garlic", name: "กระเทียม", nameEn: "Garlic", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 4,
    per100: { calories: 300.0, protein: 1.7, carbs: 10.0, fat: 26.7, sodium: 866.7, sugar: 6.7 },
    allergens: ["egg"] },
  { slug: "honey_mustard", name: "ฮันนี่มัสตาร์ด", nameEn: "Honey Mustard", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 5,
    per100: { calories: 283.3, protein: 2.0, carbs: 33.3, fat: 16.7, sodium: 966.7, sugar: 30.0 },
    allergens: ["egg"] },
  { slug: "gochujang", name: "โกชูจัง", nameEn: "Gochujang", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 6,
    per100: { calories: 233.3, protein: 3.3, carbs: 43.3, fat: 3.3, sodium: 1933.3, sugar: 30.0 },
    allergens: ["soy", "wheat"] },
  { slug: "teriyaki", name: "เทริยากิ", nameEn: "Teriyaki", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 7,
    per100: { calories: 216.7, protein: 3.3, carbs: 46.7, fat: 0.7, sodium: 2300.0, sugar: 40.0 },
    allergens: ["soy", "wheat"] },
  { slug: "ponzu", name: "พอนสึ", nameEn: "Ponzu", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 8,
    per100: { calories: 83.3, protein: 3.3, carbs: 13.3, fat: 0.0, sodium: 1800.0, sugar: 10.0 },
    allergens: ["soy", "fish"] },
  { slug: "balsamic", name: "บัลซามิก", nameEn: "Balsamic", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 9,
    per100: { calories: 233.3, protein: 0.7, carbs: 20.0, fat: 16.7, sodium: 350.0, sugar: 16.7 },
    allergens: [] },
  { slug: "yogurt", name: "โยเกิร์ต", nameEn: "Yogurt", step: "sauce", role: "fat",
    unit: "ml", portionSize: 30, gramsPerPiece: null, price: 0, sort: 10,
    per100: { calories: 150.0, protein: 8.3, carbs: 13.3, fat: 6.7, sodium: 250.0, sugar: 11.7 },
    allergens: ["milk"] },
  { slug: "sesame_roasted", name: "งาขาวคั่ว", nameEn: "Roasted Sesame", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 1,
    per100: { calories: 600.0, protein: 20.0, carbs: 20.0, fat: 54.0, sodium: 20.0, sugar: 0.0 },
    allergens: ["sesame"] },
  { slug: "sesame_black", name: "งาดำ", nameEn: "Black Sesame", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 2,
    per100: { calories: 600.0, protein: 20.0, carbs: 20.0, fat: 54.0, sodium: 20.0, sugar: 0.0 },
    allergens: ["sesame"] },
  { slug: "crispy_garlic", name: "กระเทียมเจียว", nameEn: "Crispy Garlic", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 3,
    per100: { calories: 700.0, protein: 10.0, carbs: 40.0, fat: 56.0, sodium: 500.0, sugar: 0.0 },
    allergens: [] },
  { slug: "crispy_onion", name: "หอมเจียว", nameEn: "Crispy Onion", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 4,
    per100: { calories: 800.0, protein: 8.0, carbs: 60.0, fat: 60.0, sodium: 600.0, sugar: 10.0 },
    allergens: [] },
  { slug: "spring_onion", name: "ต้นหอมซอย", nameEn: "Spring Onion", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 5,
    per100: { calories: 60.0, protein: 4.0, carbs: 12.0, fat: 0.0, sodium: 40.0, sugar: 4.0 },
    allergens: [] },
  { slug: "seaweed_flakes", name: "สาหร่ายโรย", nameEn: "Seaweed Flakes", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 6,
    per100: { calories: 160.0, protein: 16.0, carbs: 20.0, fat: 2.0, sodium: 1900.0, sugar: 0.0 },
    allergens: [] },
  { slug: "furikake", name: "ฟุริคาเกะ", nameEn: "Furikake", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 7,
    per100: { calories: 300.0, protein: 20.0, carbs: 30.0, fat: 14.0, sodium: 3200.0, sugar: 6.0 },
    allergens: ["fish", "sesame", "soy"] },
  { slug: "chili_flakes", name: "พริกป่น", nameEn: "Chili Flakes", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 8,
    per100: { calories: 100.0, protein: 4.0, carbs: 20.0, fat: 4.0, sodium: 20.0, sugar: 0.0 },
    allergens: [] },
  { slug: "coriander", name: "ผักชี", nameEn: "Coriander", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 9,
    per100: { calories: 40.0, protein: 4.0, carbs: 6.0, fat: 0.0, sodium: 40.0, sugar: 0.0 },
    allergens: [] },
  { slug: "black_pepper", name: "พริกไทยดำ", nameEn: "Black Pepper", step: "finish", role: "other",
    unit: "g", portionSize: 5, gramsPerPiece: null, price: 0, sort: 10,
    per100: { calories: 60.0, protein: 2.0, carbs: 14.0, fat: 0.0, sodium: 0.0, sugar: 0.0 },
    allergens: [] },
];
